# Generated by Django 2.2.5 on 2020-05-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_desription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desription',
            new_name='description',
        ),
    ]
