# Generated by Django 2.2.5 on 2020-05-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrafields',
            old_name='user_name',
            new_name='user',
        ),
    ]
