# Generated by Django 2.2.5 on 2020-05-14 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200514_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafields',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
