# Generated by Django 2.2.5 on 2020-05-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_extrafields_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='birthdate',
            field=models.DateField(verbose_name='DOB'),
        ),
    ]
